//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTheRecreation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rest
    {
        public int Id { get; set; }
        public string NameTour { get; set; }
        public Nullable<int> NumberSchool { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string NameTeacher { get; set; }
        public Nullable<int> CountOfChildren { get; set; }
        public string PhoneNumber { get; set; }
        public string NextTour { get; set; }
        public Nullable<bool> GAI { get; set; }
        public Nullable<decimal> Money { get; set; }
        public string Comment { get; set; }
        public string Email { get; set; }
    }
}
