//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTheRecreation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestDatabaseEntities : DbContext
    {
        public RestDatabaseEntities()
            : base("name=RestDatabaseEntities")
        {
           //this.Database.Connection.ConnectionString =
           //    @"Data Source=ALEX-PC\SQLEXPRESS;Initial Catalog=RestDatabase;Integrated Security=True";
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rest> Rests { get; set; }
    }
}
